version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  linting:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: .circleci/ci-requirements.txt
          pkg-manager: pip
      - run:
          name: Run tests
          command: yapf -d --recursive rlmeta

workflows:
  main:
    jobs:
      - linting